#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace smtp_client
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ABGSC_DW")]
	public partial class SQLDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertsmtp_mail_batch(smtp_mail_batch instance);
    partial void Updatesmtp_mail_batch(smtp_mail_batch instance);
    partial void Deletesmtp_mail_batch(smtp_mail_batch instance);
    #endregion
		
		public SQLDataClassesDataContext() : 
				base(global::smtp_client.Settings.Default.ABGSC_DWConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SQLDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<smtp_mail_batch> smtp_mail_batches
		{
			get
			{
				return this.GetTable<smtp_mail_batch>();
			}
		}
		
		public System.Data.Linq.Table<smtp_mail_batch_detail> smtp_mail_batch_details
		{
			get
			{
				return this.GetTable<smtp_mail_batch_detail>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smtp_mail_batch")]
	public partial class smtp_mail_batch : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private string _smtp_server_host;
		
		private System.Nullable<int> _smtp_port;
		
		private string _smtp_user;
		
		private string _smtp_password;
		
		private string _description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void Onsmtp_server_hostChanging(string value);
    partial void Onsmtp_server_hostChanged();
    partial void Onsmtp_portChanging(System.Nullable<int> value);
    partial void Onsmtp_portChanged();
    partial void Onsmtp_userChanging(string value);
    partial void Onsmtp_userChanged();
    partial void Onsmtp_passwordChanging(string value);
    partial void Onsmtp_passwordChanged();
    partial void OndescriptionChanging(string value);
    partial void OndescriptionChanged();
    #endregion
		
		public smtp_mail_batch()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_server_host", DbType="VarChar(1024)")]
		public string smtp_server_host
		{
			get
			{
				return this._smtp_server_host;
			}
			set
			{
				if ((this._smtp_server_host != value))
				{
					this.Onsmtp_server_hostChanging(value);
					this.SendPropertyChanging();
					this._smtp_server_host = value;
					this.SendPropertyChanged("smtp_server_host");
					this.Onsmtp_server_hostChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_port", DbType="Int")]
		public System.Nullable<int> smtp_port
		{
			get
			{
				return this._smtp_port;
			}
			set
			{
				if ((this._smtp_port != value))
				{
					this.Onsmtp_portChanging(value);
					this.SendPropertyChanging();
					this._smtp_port = value;
					this.SendPropertyChanged("smtp_port");
					this.Onsmtp_portChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_user", DbType="VarChar(1024)")]
		public string smtp_user
		{
			get
			{
				return this._smtp_user;
			}
			set
			{
				if ((this._smtp_user != value))
				{
					this.Onsmtp_userChanging(value);
					this.SendPropertyChanging();
					this._smtp_user = value;
					this.SendPropertyChanged("smtp_user");
					this.Onsmtp_userChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_password", DbType="VarChar(1024)")]
		public string smtp_password
		{
			get
			{
				return this._smtp_password;
			}
			set
			{
				if ((this._smtp_password != value))
				{
					this.Onsmtp_passwordChanging(value);
					this.SendPropertyChanging();
					this._smtp_password = value;
					this.SendPropertyChanged("smtp_password");
					this.Onsmtp_passwordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(1024)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this.OndescriptionChanging(value);
					this.SendPropertyChanging();
					this._description = value;
					this.SendPropertyChanged("description");
					this.OndescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.smtp_mail_batch_details")]
	public partial class smtp_mail_batch_detail
	{
		
		private string _mail_id;
		
		private int _smtp_batch_ID;
		
		private string _mime_sender;
		
		private string _mime_sender_name;
		
		private string _mime_from_list;
		
		private string _mime_from_name_list;
		
		private string _mime_to_list;
		
		private string _mime_to_name_list;
		
		private string _mime_cc_list;
		
		private string _mime_bcc_list;
		
		private string _mime_attachment_list;
		
		private string _mime_textpart;
		
		private string _mime_htmlpart;
		
		private string _mime_subject;
		
		public smtp_mail_batch_detail()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mail_id", DbType="VarChar(50)")]
		public string mail_id
		{
			get
			{
				return this._mail_id;
			}
			set
			{
				if ((this._mail_id != value))
				{
					this._mail_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_smtp_batch_ID", DbType="Int NOT NULL")]
		public int smtp_batch_ID
		{
			get
			{
				return this._smtp_batch_ID;
			}
			set
			{
				if ((this._smtp_batch_ID != value))
				{
					this._smtp_batch_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_sender", DbType="VarChar(1024)")]
		public string mime_sender
		{
			get
			{
				return this._mime_sender;
			}
			set
			{
				if ((this._mime_sender != value))
				{
					this._mime_sender = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_sender_name", DbType="VarChar(1024)")]
		public string mime_sender_name
		{
			get
			{
				return this._mime_sender_name;
			}
			set
			{
				if ((this._mime_sender_name != value))
				{
					this._mime_sender_name = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_from_list", DbType="VarChar(1024)")]
		public string mime_from_list
		{
			get
			{
				return this._mime_from_list;
			}
			set
			{
				if ((this._mime_from_list != value))
				{
					this._mime_from_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_from_name_list", DbType="VarChar(1024)")]
		public string mime_from_name_list
		{
			get
			{
				return this._mime_from_name_list;
			}
			set
			{
				if ((this._mime_from_name_list != value))
				{
					this._mime_from_name_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_to_list", DbType="VarChar(1024)")]
		public string mime_to_list
		{
			get
			{
				return this._mime_to_list;
			}
			set
			{
				if ((this._mime_to_list != value))
				{
					this._mime_to_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_to_name_list", DbType="VarChar(1024)")]
		public string mime_to_name_list
		{
			get
			{
				return this._mime_to_name_list;
			}
			set
			{
				if ((this._mime_to_name_list != value))
				{
					this._mime_to_name_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_cc_list", DbType="VarChar(1024)")]
		public string mime_cc_list
		{
			get
			{
				return this._mime_cc_list;
			}
			set
			{
				if ((this._mime_cc_list != value))
				{
					this._mime_cc_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_bcc_list", DbType="VarChar(1024)")]
		public string mime_bcc_list
		{
			get
			{
				return this._mime_bcc_list;
			}
			set
			{
				if ((this._mime_bcc_list != value))
				{
					this._mime_bcc_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_attachment_list", DbType="VarChar(1024)")]
		public string mime_attachment_list
		{
			get
			{
				return this._mime_attachment_list;
			}
			set
			{
				if ((this._mime_attachment_list != value))
				{
					this._mime_attachment_list = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_textpart", DbType="VarChar(2048)")]
		public string mime_textpart
		{
			get
			{
				return this._mime_textpart;
			}
			set
			{
				if ((this._mime_textpart != value))
				{
					this._mime_textpart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_htmlpart", DbType="VarChar(2048)")]
		public string mime_htmlpart
		{
			get
			{
				return this._mime_htmlpart;
			}
			set
			{
				if ((this._mime_htmlpart != value))
				{
					this._mime_htmlpart = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mime_subject", DbType="VarChar(1024)")]
		public string mime_subject
		{
			get
			{
				return this._mime_subject;
			}
			set
			{
				if ((this._mime_subject != value))
				{
					this._mime_subject = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
